version: "3.9"
services:
  postgres:
    container_name: covid-postgres-geolocation
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: geolocation_covid
    ports:
      - '5439:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql